module.exports.firstNames = [
    'James',
    'John',
    'Robert',
    'Michael',
    'William',
    'David',
    'Richard',
    'Joseph',
    'Thomas',
    'Charles',
    'Christopher',
    'Daniel',
    'Matthew',
    'Mary',
    'Patricia',
    'Jennifer',
    'Linda',
    'Elizabeth',
    'Barbara',
    'Susan',
    'Jessica',
    'Sarah',
    'Karen',
    'Nancy',
    'Lisa',
    'Margaret',
    'Betty',
    'Sandra',
    'Ashley',
    'Dorothy',
    'Kimberly',
    'Emily',
    'Donna',
    'Michelle',
    'Carol',
    'Amanda',
    'Melissa',
    'Deborah',
    'Stephanie',
    'Rebecca',
    'Laura',
    'Sharon',
    'Cynthia',
    'Kathleen',
    'Amy',
    'Shirley',
    'Angela',
    'Helen',
    'Anna'
]

module.exports.lastNames = [
    'Smith',
    'Brown',
    'Tremblay',
    'Martin',
    'Roy',
    'Gagnon',
    'Lee',
    'Wilson',
    'Johnson',
    'MacDonald',
    'Taylor',
    'Campbell',
    'Anderson',
    'Jones',
    'Leblanc',
    'Cote',
    'Williams',
    'Miller',
    'Thompson',
    'Gauthier',
    'White',
    'Morin',
    'Wong',
    'Young',
    'Bouchard',
    'Scott',
    'Stewart',
    'Pelletier',
    'Lavoie',
    'Robinson',
    'Moore',
    'Belanger'
]

module.exports.lastNames = [
    'Smith',
    'Brown',
    'Tremblay',
    'Martin',
    'Roy',
    'Gagnon',
    'Lee',
    'Wilson',
    'Johnson',
    'MacDonald',
    'Taylor',
    'Campbell',
    'Anderson',
    'Jones',
    'Leblanc',
    'Cote',
    'Williams',
    'Miller',
    'Thompson',
    'Gauthier',
    'White',
    'Morin',
    'Wong',
    'Young',
    'Bouchard',
    'Scott',
    'Stewart',
    'Pelletier',
    'Lavoie',
    'Robinson',
    'Moore',
    'Belanger'
]

module.exports.sports = [
    'Soccer',
    'Hockey',
    'Lacrosse',
    'Basketball',
    'Football'
]

module.exports.graduationsYears = [
    2021,
    2022,
    2023,
    2024,
    2025,
    2026
]

module.exports.highSchools = [
    'Heritage Woods Secondary School',
    'Dr. Charles Best Secondary School',
    'Glen Eagle Secondary School',
    'Pintree Secondary School',
    'Terry Fox Secondary School'
]

module.exports.postGrad = [
    true,
    false
]
